select * from clientes;
select * from empleados;
select * from tiendas;
select * from prendas;
select * from clientes where nombre_cliente like "l%";
select count(*) as total_clientes from clientes;
select * from compras where fecha_compra > '2023-05-01';
update clientes set email_cliente = 'carlos.nuevo@email.com' where id_cliente = 1;
delete from clientes where id_cliente = 4;
select * from prendas where color = "Negro";
select * from tiendas where ciudad = "Madrid";
select count(*) as prendas_mas_50 from prendas where precio > 50;
select * from empleados where id_empleado = 1;
select * from clientes where nombre_cliente like "%Andrés%";
select * from compras where id_cliente = 2;
delete from compras where monto_total < 30;
select * from prendas where precio between 20 and 40;
select * from empleados where nombre_empleado like "%a%";
select * from prendas order by precio desc limit 5;
select * from compras where monto_total > 75 limit 1;
select * from prendas where talla like "M";
update prendas SET talla = 'L' WHERE id_prenda = 1;
select * from empleados where fecha_contratacion > "2022-01-01";
select * from tiendas where ciudad = "Barcelona";
delete from empleados WHERE id_empleado = 5;
select * from compras where fecha_compra < "2023-07-01";
select * from prendas where tipo_prenda like "%eta";
select * from clientes where email_cliente not like "%hotmail%";
select count(*) from compras where fecha_compra BETWEEN '2023-09-01' AND '2023-09-30';
update tienda set direccion = 'Calle Gran Vía, 45' WHERE id_tienda = 1;
select * from prendas where tipo_prenda like "%Camiseta%";
delete from prendas where precio < 20;
select * from tiendas order by ciudad;
select * from empleados where puesto like "%vendedor%";
select count(*) as prendas_blancas from prendas where color like "%blanco%";
select * from clientes where char_length(nombre_cliente) > 10;
select * from compras where monto_total between 50 and 100;
select * from compras order by fecha_compra desc limit 3;
no existe tabla cursos
select color, COUNT(*) as total from prendas group by color;
insert into tiendas (nombre_tienda, direccion, ciudad, pais) values ("zara serrano", "calle de serrano, 23", "Madrid", "España"), ("zara príncipe pio", "paseo de la florida, 2", "Madrid", "España");
update clientes set nombre_cliente = "Micaela Torres", email_cliente = "micaela.torres@email.com" where nombre_cliente = "Miguel Torres";