SELECT c.nombre_cliente, co.monto_total FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente;
SELECT e.nombre_empleado, t.nombre_tienda FROM Empleados e JOIN Tiendas t ON e.tienda_id = t.id_tienda;
SELECT DISTINCT p.tipo_prenda, c.nombre_cliente FROM Prendas p JOIN Detalle_Compras d ON p.id_prenda = d.id_prenda JOIN Compras co ON d.id_compra = co.id_compra JOIN Clientes c ON co.id_cliente = c.id_cliente;
SELECT c.nombre_cliente, COUNT(co.id_compra) AS num_compras FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente GROUP BY c.id_cliente, c.nombre_cliente;
SELECT DISTINCT e.nombre_empleado, p.tipo_prenda FROM Empleados e JOIN Compras co ON e.id_empleado = co.id_empleado JOIN Detalle_Compras d ON co.id_compra = d.id_compra JOIN Prendas p ON d.id_prenda = p.id_prenda WHERE p.color = 'Rojo';
SELECT t.nombre_tienda, SUM(d.cantidad) AS prendas_vendidas FROM Tiendas t JOIN Compras co ON t.id_tienda = co.id_tienda JOIN Detalle_Compras d ON co.id_compra = d.id_compra GROUP BY t.id_tienda, t.nombre_tienda;
SELECT c.nombre_cliente, co.monto_total FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente WHERE co.monto_total > 100;
SELECT p.tipo_prenda, SUM(d.cantidad) AS cantidad_vendida FROM Prendas p JOIN Detalle_Compras d ON p.id_prenda = d.id_prenda GROUP BY p.id_prenda, p.tipo_prenda;
SELECT p.tipo_prenda, COUNT(DISTINCT co.id_cliente) AS num_clientes FROM Prendas p JOIN Detalle_Compras d ON p.id_prenda = d.id_prenda JOIN Compras co ON d.id_compra = co.id_compra GROUP BY p.id_prenda, p.tipo_prenda HAVING COUNT(DISTINCT co.id_cliente) > 1;
SELECT c.nombre_cliente, co.monto_total, co.fecha_compra FROM Compras co JOIN Clientes c ON co.id_cliente = c.id_cliente WHERE co.id_tienda = 1;
SELECT e.nombre_empleado, t.nombre_tienda FROM Empleados e JOIN Tiendas t ON e.tienda_id = t.id_tienda WHERE t.ciudad = 'Madrid';
SELECT c.nombre_cliente, c.email_cliente FROM Clientes c LEFT JOIN Compras co ON c.id_cliente = co.id_cliente WHERE co.id_compra IS NULL;
SELECT t.nombre_tienda, COUNT(e.id_empleado) AS num_empleados FROM Tiendas t JOIN Empleados e ON t.id_tienda = e.tienda_id GROUP BY t.id_tienda, t.nombre_tienda ORDER BY num_empleados DESC LIMIT 1;
SELECT e.nombre_empleado, SUM(co.monto_total) AS total_vendido FROM Empleados e JOIN Compras co ON e.id_empleado = co.id_empleado GROUP BY e.id_empleado, e.nombre_empleado;
SELECT c.nombre_cliente, co.fecha_compra FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente WHERE co.fecha_compra BETWEEN '2023-09-01' AND '2023-09-30';
SELECT DISTINCT c.nombre_cliente, t.nombre_tienda FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente JOIN Tiendas t ON co.id_tienda = t.id_tienda;
SELECT tipo_prenda, AVG(precio) AS precio_promedio FROM Prendas GROUP BY tipo_prenda HAVING AVG(precio) > 40;
SELECT e.nombre_empleado, COUNT(co.id_compra) AS compras_gestionadas FROM Empleados e LEFT JOIN Compras co ON e.id_empleado = co.id_empleado GROUP BY e.id_empleado, e.nombre_empleado;
SELECT c.nombre_cliente, COUNT(co.id_compra) AS num_compras FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente GROUP BY c.id_cliente, c.nombre_cliente HAVING COUNT(co.id_compra) > 3;
SELECT p.tipo_prenda, SUM(p.precio * d.cantidad) AS total_vendido FROM Prendas p JOIN Detalle_Compras d ON p.id_prenda = d.id_prenda GROUP BY p.id_prenda, p.tipo_prenda;
SELECT c.nombre_cliente, SUM(co.monto_total) AS total, CASE WHEN SUM(co.monto_total) < 100 THEN 'Bajo' WHEN SUM(co.monto_total) <= 250 THEN 'Medio' ELSE 'Alto' END AS categoria FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente GROUP BY c.id_cliente, c.nombre_cliente;
UPDATE Prendas SET precio = precio * 1.10 WHERE tipo_prenda = 'Zapatos';
ALTER TABLE Clientes ADD COLUMN telefono_cliente VARCHAR(20);
SELECT c.nombre_cliente, COUNT(co.id_compra) AS num_compras, AVG(co.monto_total) AS gasto_promedio FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente GROUP BY c.id_cliente, c.nombre_cliente;
DELETE FROM Prendas WHERE precio < 10;
SELECT c.nombre_cliente, SUM(co.monto_total) AS total_gastado FROM Clientes c JOIN Compras co ON c.id_cliente = co.id_cliente GROUP BY c.id_cliente, c.nombre_cliente;
SELECT t.nombre_tienda, e.nombre_empleado, COUNT(co.id_compra) AS compras_gestionadas FROM Tiendas t JOIN Empleados e ON t.id_tienda = e.tienda_id LEFT JOIN Compras co ON e.id_empleado = co.id_empleado GROUP BY t.id_tienda, t.nombre_tienda, e.id_empleado, e.nombre_empleado;
SELECT nombre_cliente FROM Clientes WHERE id_cliente = (SELECT id_cliente FROM Compras WHERE monto_total = (SELECT MAX(monto_total) FROM Compras) LIMIT 1);
ALTER TABLE Empleados ADD COLUMN ciudad VARCHAR(100); UPDATE Empleados SET ciudad = 'Madrid' WHERE tienda_id = (SELECT id_tienda FROM Tiendas WHERE nombre_tienda = 'Zara Gran Vía');
SELECT c.nombre_cliente FROM Clientes c WHERE EXISTS (SELECT 1 FROM Compras co WHERE co.id_cliente = c.id_cliente);