use sakila;
select * from actor;
select * from film;
select * from customer;
select title from film;
select distinct name as language from language;
select count(*) as "total_stores" from store;
select count(*) as "total_staff" from staff;
select first_name as "staff_name" from staff;
select * from actor where first_name = "Scarlett";
select * from actor where last_name = "Johansson";
select count(distinct film_id) as "films_available" from inventory;
select count(distinct f.film_id) as "films_rented" from rental r join inventory i on r.inventory_id = i.inventory_id join film f on i.film_id = f.film_id;
select min(rental_duration) as mas_corto, max(rental_duration) as mas_largo from film;
select min(length) as min_duration, max(length) as max_duration from film;
select avg(length) as average_duration from film;
select CONCAT(FLOOR(AVG(length)/60), ' hours ', ROUND(AVG(length)%60), ' minutes') AS average_duration FROM film;
select count(*) as films_over_3h from film where length>=180;
SELECT MAX(LENGTH(title)) AS longest_title FROM film;